<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\GamePause.App\Assets\game-pause.ico</ApplicationIcon>
    <AssemblyName>GamePause.Updater</AssemblyName>
    <Version>1.2.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GamePause.Core\GamePause.Core.csproj" />
  </ItemGroup>
</Project>
